name: 'setup jdk and sbt cache'
description: 'Checkout Repo / Setup JDK / sbt-cache by SO'

inputs:
  token:
    required: true
    description: 'token to checkout repo'
  fetch-depth:
    required: false
    description: 'fetch-depth to checkout repo'
    default: '1'
  jdk-version:
    required: false
    description: 'jdk version'
    default: '8'

runs:
  using: "composite"
  steps:
    - name: Clone Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        token: ${{ inputs.token }}

    - name: Set up JDK ${{ inputs.jdk-version }}
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: ${{ inputs.jdk-version }}

    - name: SBT Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier
          ~/.cache/coursier
        key: sbt-cache-${{ runner.os }}-${{ matrix.target-platform }}-${{ hashFiles('project/build.properties') }}

